export default {
  sequency: [
    "t",
    "tr",
    "tra",
    "trav",
    "trava",
    "travai",
    "travail",
    "travaill",
    "travaille",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travaille",
    "travaill",
    "travail",
    "travai",
    "trava",
    "trav",
    "tra",
    "tr",
    "t",
    "",
    "é",
    "éc",
    "éch",
    "écha",
    "échan",
    "échang",
    "échange",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échange",
    "échang",
    "échan",
    "écha",
    "éch",
    "éc",
    "é",
    "",
    "d",
    "di",
    "dis",
    "disr",
    "disru",
    "disrup",
    "disrupt",
    "disrupte",
    "disrupter",
    "disrupter 😀",
    "disrupter 😀",
    "disrupter 😁",
    "disrupter 😁",
    "disrupter 😉",
    "disrupter 😉",
    "disrupter 🌈",
    "disrupter 🌈",
    "disrupter 🌊",
    "disrupter 🌊",
    "disrupter 🌴",
    "disrupter 🌴",
    "disrupter 🌼",
    "disrupter 🌼",
    "disrupter 🍍",
    "disrupter 🍍",
    "disrupter 🎷",
    "disrupter 🎷",
    "disrupter 👀",
    "disrupter 👀",
    "disrupter",
    "disrupte",
    "disrupt",
    "disrup",
    "disru",
    "disr",
    "dis",
    "di",
    "d",
    "",
  ],
  sequency2: [
    "t",
    "tr",
    "tra",
    "trav",
    "trava",
    "travai",
    "travail",
    "travaill",
    "travaille",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travailler",
    "travaille",
    "travaill",
    "travail",
    "travai",
    "trava",
    "trav",
    "tra",
    "tr",
    "t",
    "",
    "é",
    "éc",
    "éch",
    "écha",
    "échan",
    "échang",
    "échange",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échanger",
    "échange",
    "échang",
    "échan",
    "écha",
    "éch",
    "éc",
    "é",
    "",
    "d",
    "di",
    "dis",
    "disr",
    "disru",
    "disrup",
    "disrupt",
    "disrupte",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupter",
    "disrupte",
    "disrupt",
    "disrup",
    "disru",
    "disr",
    "dis",
    "di",
    "d",
    "",
  ],
}
